version: "3.9"

services:
  backend:
    image: translate-backend:latest
    build:
      context: ./translate-pdf-app_BACKEND
    ports:
      - "8000:8000"
    volumes:
      - input:/app/input:rw
      - output:/app/output:rw
    restart: always
    environment:
      - FRONTEND_ORIGIN=http://localhost:5173
      - FRONTEND_HOST=https://fe-08u9.onrender.com
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- https://backend-app-98fp.onrender.com/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: translate-frontend:latest
    build:
      context: ./translate-pdf-app_FRONTEND
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
volumes:
  input:
  output:
